//!
//! @file id_plane_def.hpp
//! @author jbruel
//! @date 16/02/19
//!

#ifndef FAILLIST_ID_PLANE_DEF_HPP
# define FAILLIST_ID_PLANE_DEF_HPP

# include "report/id_plane/id_plane.h"

//!
//! @def MAX_ID_PLANE
//! @brief Max ID Plane.
//!
# define MAX_ID_PLANE   451

//!
//! @static
//! @def static const struct type_plane  type_planes[MAX_ID_PLANE]
//! @brief All id planes.
//!
static const struct id_plane    id_planes[MAX_ID_PLANE] = {
        {"Afghanistan", "YA"},
        {"Albania", "ZA"},
        {"Algeria", "7T"},
        {"Andorra", "C3"},
        { "Angola", "D2" },
        { "Anguilla", "VP-A" },
        { "Antigua and Barbuda", "V2" },
        { "Argentina", "LV" },
        { "Argentina", "LQ" },
        { "Armenia", "EK" },
        { "Aruba", "P4" },
        { "Australia", "VH" },
        { "Austria", "OE" },
        { "Azerbaijan", "4K" },
        { "Bahamas", "C6" },
        { "Bahrain", "A9C" },
        { "Bangladesh", "S2" },
        { "Barbados", "8P" },
        { "Belarus", "EW" },
        { "Belgium", "OO" },
        { "Belize", "V3" },
        { "Benin", "TY" },
        { "Bermuda", "VP-B" },
        { "Bermuda", "VQ-B" },
        { "Bhutan", "A5" },
        { "Bolivia", "CP" },
        { "Bosnia and Herzegovina", "T9" },
        { "Bosnia and Herzegovina", "E7" },
        { "Botswana", "A2" },
        { "Brazil", "PP" },
        { "Brazil", "PR" },
        { "Brazil", "PS" },
        { "Brazil", "PT" },
        { "Brazil", "PU" },
        { "British Virgin Islands", "VP-L" },
        { "Brunei", "V8" },
        { "Bulgaria", "LZ" },
        { "Burkina Faso", "XT" },
        { "Burundi", "9U" },
        { "Cambodia", "XU" },
        { "Cameroon", "TJ" },
        { "Canada", "C" },
        { "Cape Verde", "D4" },
        { "Cayman Islands", "VP-C" },
        { "Central African Republic", "TL" },
        { "Chad", "TT" },
        { "Chile", "CC" },
        { "Republic of China (Taiwan)", "B" },
        { "People's Republic of China", "B" },
        { "Hong Kong", "B-H" },
        { "Macau", "B-M" },
        { "Colombia", "HJ" },
        { "Colombia", "HK" },
        { "Comoros", "D6" },
        { "Congo, Republic of", "TN" },
        { "Cook Islands", "E5" },
        { "Congo, Democratic Republic of", "9Q" },
        { "Costa Rica", "TI" },
        { "Côte d'Ivoire", "TU" },
        { "Croatia", "9A" },
        { "Cuba", "CU" },
        { "Cyprus, Republic of", "5B" },
        { "Czech Republic", "OK" },
        { "Denmark", "OY" },
        { "Djibouti", "J2" },
        { "Dominica", "J7" },
        { "Dominican Republic", "HI" },
        { "East Timor", "4W" },
        { "Ecuador", "HC" },
        { "Egypt", "SU" },
        { "El Salvador", "YS" },
        { "Equatorial Guinea", "3C" },
        { "Eritrea", "E3" },
        { "Estonia", "ES" },
        { "Ethiopia", "ET" },
        { "Falkland Islands", "VP-F" },
        { "Faroe Islands", "See Denmark" },
        { "Fiji Islands", "DQ" },
        { "Finland", "OH" },
        { "France", "F" },
        { "French West Indies", "F-OG" },
        { "French Guyana", "F-O" },
        { "Gabon", "TR" },
        { "Gambia", "C5" },
        { "Georgia", "4L" },
        { "Germany", "D" },
        { "Ghana", "9G" },
        { "Gibraltar", "VP-G" },
        { "Greece", "SX" },
        { "Greenland", "See Denmark" },
        { "Grenada", "J3" },
        { "Guatemala", "TG" },
        { "Guernsey", "2" },
        { "Guinea", "3X" },
        { "Guinea Bissau", "J5" },
        { "Guyana", "8R" },
        { "Haiti", "HH" },
        { "Honduras", "HR" },
        { "Hungary", "HA" },
        { "Iceland", "TF" },
        { "India", "VT" },
        { "Indonesia", "PK" },
        { "Iran", "EP" },
        { "Iraq", "YI" },
        { "Ireland", "EI" },
        { "Israel", "4X" },
        { "Italy", "I" },
        { "Jamaica", "6Y" },
        { "Japan", "JA" },
        { "Jersey", "ZJ" },
        { "Jordan", "JY" },
        { "Kosovo, Republic of", "Z6" },
        { "Kazakhstan", "UP" },
        { "Kenya", "5Y" },
        { "Kiribati", "T3" },
        { "Korea, People's Democratic Rep.", "P" },
        { "Korea, Republic of", "HL" },
        { "Kuwait", "9K" },
        { "Kyrgyzstan", "EX" },
        { "Laos", "RDPL" },
        { "Latvia", "YL" },
        { "Lebanon", "OD" },
        { "Lesotho", "7P" },
        { "Liberia", "A8" },
        { "Libya", "5A" },
        { "Liechtenstein", "HB" },
        { "Lithuania", "LY" },
        { "Luxembourg", "LX" },
        { "Macedonia, Republic of", "Z3" },
        { "Madagascar", "5R" },
        { "Malawi", "7Q" },
        { "Malaysia", "9M" },
        { "Maldives", "8Q" },
        { "Mali", "TZ" },
        { "Malta", "9H" },
        { "Isle of Man", "M" },
        { "Marshall Islands", "V7" },
        { "Mauritania", "5T" },
        { "Mauritius", "3B" },
        { "Mexico", "XA" },
        { "Mexico", "XB" },
        { "Mexico", "XC" },
        { "Micronesia, Federated States of", "V6" },
        { "Moldova", "ER" },
        { "Monaco", "3A" },
        { "Mongolia", "JU" },
        { "Montenegro", "4O" },
        { "Montserrat", "VP-M" },
        { "Morocco", "CN" },
        { "Mozambique", "C9" },
        { "Myanmar", "XY" },
        { "Myanmar", "XZ" },
        { "Namibia", "V5" },
        { "Nauru", "C2" },
        { "Nepal", "9N" },
        { "Netherlands", "PH" },
        { "Netherlands Antilles", "PJ" },
        { "New Zealand", "ZK" },
        { "Nicaragua", "YN" },
        { "Niger", "5U" },
        { "Nigeria", "5N" },
        { "Norway", "LN" },
        { "Oman", "A4O" },
        { "Pakistan", "AP" },
        { "Palestine", "E4" },
        { "Panama", "HP" },
        { "Papua New Guinea", "P2" },
        { "Paraguay", "ZP" },
        { "Peru", "OB" },
        { "Philippines", "RP" },
        { "Poland", "SP" },
        { "Poland", "SN" },
        { "Portugal", "CR" },
        { "Portugal", "CS" },
        { "Qatar", "A7" },
        { "Réunion Island", "F-OD" },
        { "Romania", "YR" },
        { "Russian Federation", "RA" },
        { "Russian Federation","RF" },
        { "Rwanda", "9XR" },
        { "Saint Helena/Ascension", "VQ-H" },
        { "Saint Kitts and Nevis", "V4" },
        { "Saint Lucia", "J6" },
        { "Saint Vincent and the Grenadines", "J8" },
        { "Samoa", "5W" },
        { "San Marino", "T7" },
        { "São Tomé and Príncipe", "S9" },
        { "Saudi Arabia", "HZ" },
        { "Senegal", "6V" },
        { "Serbia", "YU" },
        { "Seychelles", "S7" },
        { "Sierra Leone", "9L" },
        { "Singapore", "9V" },
        { "Slovakia", "OM" },
        { "Slovenia", "S5" },
        { "Solomon Islands", "H4" },
        { "Somalia", "6O" },
        { "South Africa", "ZS" },
        { "South Africa","ZT" },
        { "South Africa","ZU" },
        { "South Sudan", "Z8" },
        { "Spain", "EC" },
        { "Sri Lanka", "4R" },
        { "Sudan", "ST" },
        { "Surinam", "PZ" },
        { "Swaziland", "3D" },
        { "Sweden", "SE" },
        { "Switzerland", "HB" },
        { "Syria", "YK" },
        { "Tahiti", "F-OH" },
        { "Tajikistan", "EY" },
        { "Tanzania", "5H" },
        { "Thailand", "HS" },
        { "Togo", "5V" },
        { "Tonga", "A3" },
        { "Trinidad and Tobago", "9Y" },
        { "Tunisia", "TS" },
        { "Turkey", "TC" },
        { "Turkmenistan", "EZ" },
        { "Turks and Caicos", "VQ-T" },
        { "Tuvalu", "T2" },
        { "Uganda", "5X" },
        { "Ukraine", "UR" },
        { "United Arab Emirates", "A6" },
        { "United Kingdom", "G" },
        { "United Nations[d]", "4U" },
        { "United States of America", "N" },
        { "Uruguay", "CX" },
        { "Uzbekistan", "UK" },
        { "Vanuatu", "YJ" },
        { "Venezuela", "YV" },
        { "Vietnam", "VN" },
        { "Yemen", "7O" },
        { "Zambia", "9J" },
        { "Zimbabwe", "Z" }
};

#endif //FAILLIST_ID_PLANE_DEF_HPP
